"""convert_strings_to_enums

Revision ID: e082266958a5
Revises: 461a2ed723ad
Create Date: 2026-08-28 19:19:21.578213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e082266958a5'
down_revision: Union[str, Sequence[str], None] = '461a2ed723ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Scheduled', 'In Progress', 'Completed', 'Cancelled', name='tripstatus').create(op.get_bind())
    sa.Enum('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='roleenum').create(op.get_bind())
    sa.Enum('Scheduled', 'In Progress', 'Completed', 'Cancelled', name='maintenancestatus').create(op.get_bind())
    sa.Enum('Available', 'Assigned', 'Maintenance', 'In Transit', name='vehiclestatus').create(op.get_bind())

    op.execute("UPDATE trips SET status = 'In Progress' WHERE status = 'In Transit'")
    op.execute("UPDATE vehicle_maintenance SET status = 'Scheduled' WHERE status IS NULL")

    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Scheduled', 'In Progress', 'Completed', 'Cancelled', name='tripstatus'),
               existing_nullable=False, postgresql_using='status::tripstatus')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='roleenum'),
               existing_nullable=False, postgresql_using='role::roleenum')
    op.alter_column('vehicle_maintenance', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Scheduled', 'In Progress', 'Completed', 'Cancelled', name='maintenancestatus'),
               nullable=False, postgresql_using='status::maintenancestatus')
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('Available', 'Assigned', 'Maintenance', 'In Transit', name='vehiclestatus'),
               existing_nullable=False, postgresql_using='status::vehiclestatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=sa.Enum('Available', 'Assigned', 'Maintenance', 'In_Transit', name='vehiclestatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('vehicle_maintenance', 'status',
               existing_type=sa.Enum('Scheduled', 'In_Progress', 'Completed', 'Cancelled', name='maintenancestatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='roleenum'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.Enum('Scheduled', 'In_Progress', 'Completed', 'Cancelled', name='tripstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
